# .github/workflows/tests.yml
name: doxie-consumer | tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  testing:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build testing Image
        id: build-testing-image
        run: docker image build --file .docker/Dockerfile --target test --tag doxie-consumer:testing .

      - name: "Linter: PHP"
        id: linter-php
        run: docker container run --rm doxie-consumer:testing vendor/bin/php-cs-fixer check --diff --stop-on-violation

      - name: Run Tests
        id: run-tests
        run: docker container run --rm doxie-consumer:testing

  notification:
    runs-on: ubuntu-latest
    needs:  # make sure the notification is sent AFTER the jobs you want included have completed
      - testing
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
    timeout-minutes: 15
    steps:
      - name: discord
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ github.token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
